@echo off
rem Generated by COMA roles[] starter generator.
@chcp 65001 >nul
setlocal
set "ROLE_MANIFEST=%~dp0ellmos-module.v2.json"
python -c "import unified_gui.console" >nul 2>&1
if errorlevel 1 goto coma_fallback
python -m unified_gui.console start --manifest "%ROLE_MANIFEST%" %*
exit /b %ERRORLEVEL%
:coma_fallback
echo [FALLBACK] unified-gui-Konsole fehlt; verwende COMA.
python -m coma starters run --manifest "%ROLE_MANIFEST%" %*
exit /b %ERRORLEVEL%
