#!/usr/bin/env sh
# Generated by COMA roles[] starter generator.
set -eu
starter_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
role_manifest="$starter_dir/ellmos-module.v2.json"
if python -c 'import unified_gui.console' >/dev/null 2>&1; then
  exec python -m unified_gui.console start --manifest "$role_manifest" "$@"
fi
echo '[FALLBACK] unified-gui-Konsole fehlt; verwende COMA.'
exec python -m coma starters run --manifest "$role_manifest" "$@"
